from datetime import datetime, timezone
from enum import Enum
from typing import List, Optional

from beanie import Document, Link
from pydantic import Field

from app.models.user import User


class ComplaintStatus(str, Enum):
    open = "open"
    in_progress = "in_progress"
    resolved = "resolved"


class Complaint(Document):
    """Beanie ODM document for resident complaints."""

    # Relationship
    resident_id: Link[User] = Field(..., description="Reference to the User who filed the complaint")

    # Core fields
    category: str = Field(..., min_length=1, max_length=100, description="Complaint category (e.g. road, water, electricity)")
    description: str = Field(..., min_length=10, max_length=5000, description="Detailed description of the complaint")
    status: ComplaintStatus = Field(default=ComplaintStatus.open, description="Current resolution status")

    # AI-enriched fields
    embedding: List[float] = Field(default_factory=list, description="Dense vector embedding of the complaint text")
    ai_title: Optional[str] = Field(default=None, max_length=200, description="Short title generated by AI")
    ai_urgency: Optional[str] = Field(default=None, description="AI-assessed urgency level (low/medium/high/critical)")
    ai_reasoning: Optional[str] = Field(default=None, description="AI explanation for the urgency assessment")

    # Duplicate detection
    duplicate_of: Optional[Link["Complaint"]] = Field(default=None, description="Link to the original complaint if this is a duplicate")
    similarity_score: Optional[float] = Field(default=None, ge=0.0, le=1.0, description="Cosine similarity score against the original complaint")

    # Timestamps
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp when the complaint was created",
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp of the last update",
    )

    class Settings:
        name = "complaints"

    class Config:
        populate_by_name = True
